Erp\Bundle\OauthBundle\Entity\OauthAuthCode:
  type: entity
  # repositoryClass: Erp\Bundle\CoreBundle\Infrastructure\ORM\Repository\OauthAccessToken
  table: oauth_authcode
  id:
    id:
      type: bigint
      generator:
        strategy: IDENTITY
  manyToOne:
    client:
      targetEntity: Erp\Bundle\OauthBundle\Entity\OauthClient
      joinColumn:
        name: id_oauth_client
        nullable: false
        onDelete: RESTRICT
      fetch: EAGER
  fields:
    username:
      type: string
      length: 64
      nullable: false
