parameters:
    container.autowiring.strict_mode: true

services:

  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  Erp\Bundle\OauthBundle\:
    resource: '../../*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../{Collection,Entity,Infrastructure/ORM/Repository}'

  Erp\Bundle\OauthBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  #Erp\Bundle\OauthBundle\Processor\ScopeProcessorRegistry: ~

  # erp_oauth.container.scope_processor:
  #   class: Erp\Bundle\OauthBundle\Processor\ScopeProcessor

  Erp\Bundle\OauthBundle\Infrastructure\ORM\Service\OauthSimpleCommandService:
    arguments:
      - "@doctrine.orm.oauth_entity_manager"

  Erp\Bundle\OauthBundle\Domain\CQRS\OauthSimpleCommand: '@Erp\Bundle\OauthBundle\Infrastructure\ORM\Service\OauthSimpleCommandService'

  Erp\Bundle\OauthBundle\Domain\CQRS\OauthAccessTokenQuery: '@Erp\Bundle\OauthBundle\Infrastructure\ORM\Service\OauthAccessTokenQueryService'
  Erp\Bundle\OauthBundle\Domain\CQRS\OauthRefreshTokenQuery: '@Erp\Bundle\OauthBundle\Infrastructure\ORM\Service\OauthRefreshTokenQueryService'
  Erp\Bundle\OauthBundle\Domain\CQRS\OauthAuthCodeQuery: '@Erp\Bundle\OauthBundle\Infrastructure\ORM\Service\OauthAuthCodeQueryService'
  Erp\Bundle\OauthBundle\Domain\CQRS\OauthClientQuery: '@Erp\Bundle\OauthBundle\Infrastructure\ORM\Service\OauthClientQueryService'

  Erp\Bundle\OauthBundle\Manager\OauthAccessTokenManager:
    #class: Erp\Bundle\OauthBundle\Service\OauthAccessTokenManager
    arguments:
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthAccessTokenQuery'
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthSimpleCommand'
      - "@fos_oauth_server.user_provider"
      - '@Erp\Bundle\OauthBundle\Processor\ScopeProcessorRegistry'

  Erp\Bundle\OauthBundle\Manager\OauthRefreshTokenManager:
    #class: Erp\Bundle\OauthBundle\Service\OauthRefreshTokenManager
    arguments:
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthRefreshTokenQuery'
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthSimpleCommand'
      - "@fos_oauth_server.user_provider"
      - '@Erp\Bundle\OauthBundle\Processor\ScopeProcessorRegistry'

  Erp\Bundle\OauthBundle\Manager\OauthAuthCodeManager:
    #class: Erp\Bundle\OauthBundle\Service\OauthAuthCodeManager
    arguments:
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthAuthCodeQuery'
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthSimpleCommand'
      - "@fos_oauth_server.user_provider"
      - '@Erp\Bundle\OauthBundle\Processor\ScopeProcessorRegistry'

  Erp\Bundle\OauthBundle\Manager\OauthClientManager:
    #class: Erp\Bundle\OauthBundle\Service\OauthClientManager
    arguments:
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthClientQuery'
      - '@Erp\Bundle\OauthBundle\Domain\CQRS\OauthSimpleCommand'

  Erp\Bundle\OauthBundle\Server\OAuth2:
    #class: Erp\Bundle\OauthBundle\Server\OAuth2
    arguments:
      - "@fos_oauth_server.storage"
      - "%fos_oauth_server.server.options%"
      - '@Erp\Bundle\OauthBundle\Processor\ScopeProcessorRegistry'

  erp_oauth.service.manager.oauth_access_token: '@Erp\Bundle\OauthBundle\Manager\OauthAccessTokenManager'
  erp_oauth.service.manager.oauth_refresh_token: '@Erp\Bundle\OauthBundle\Manager\OauthRefreshTokenManager'
  erp_oauth.service.manager.oauth_auth_code: '@Erp\Bundle\OauthBundle\Manager\OauthAuthCodeManager'
  erp_oauth.service.manager.oauth_client: '@Erp\Bundle\OauthBundle\Manager\OauthClientManager'
  fos_oauth_server.server: '@Erp\Bundle\OauthBundle\Server\OAuth2'
